# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('is_open', models.IntegerField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('hours', models.TextField(blank=True, null=True)),
                ('creditcards', models.IntegerField(blank=True, db_column='CreditCards', null=True)),
                ('dogsallowed', models.IntegerField(blank=True, db_column='DogsAllowed', null=True)),
                ('goodforkids', models.IntegerField(blank=True, db_column='GoodForKids', null=True)),
                ('takeout', models.IntegerField(blank=True, db_column='TakeOut', null=True)),
                ('outdoorseating', models.IntegerField(blank=True, db_column='OutdoorSeating', null=True)),
            ],
            options={
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city', models.TextField(blank=True, null=True)),
                ('city_ascii', models.TextField(blank=True, null=True)),
                ('state_id', models.TextField(blank=True, null=True)),
                ('state_name', models.TextField(blank=True, null=True)),
                ('county_fips', models.TextField(blank=True, null=True)),
                ('county_name', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('population', models.FloatField(blank=True, null=True)),
                ('density', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('military', models.TextField(blank=True, null=True)),
                ('incorporated', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('zips', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=25)),
                ('business_id', models.CharField(max_length=25)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('useful', models.IntegerField(blank=True, null=True)),
                ('funny', models.IntegerField(blank=True, null=True)),
                ('cool', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('yelping_since', models.DateTimeField(blank=True, null=True)),
                ('useful', models.IntegerField(blank=True, null=True)),
                ('funny', models.IntegerField(blank=True, null=True)),
                ('cool', models.IntegerField(blank=True, null=True)),
                ('elite', models.CharField(blank=True, max_length=100, null=True)),
                ('fans', models.IntegerField(blank=True, null=True)),
                ('average_stars', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
